// Code generated by stringer. DO NOT EDIT.

package permission

import (
	"math/bits"
	"strconv"
	"strings"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BaseDeveloper-1]
	_ = x[BaseDefault-2]
	_ = x[SplasherQueue-4]
}

const (
	_Permission_name_0 = "base:developerbase:defaultsplasher:queue"
)

var (
	_Permission_index_0 = [...]uint8{0, 14, 26, 40}
)

func (i Permission) ActiveFlags() []string {
	s := make([]string, 0, bits.OnesCount64(uint64(i)))
	if i&1 != 0 {
		i, s = i&^1, append(s, _Permission_name_0[_Permission_index_0[0]:_Permission_index_0[1]])
	}
	if i&2 != 0 {
		i, s = i&^2, append(s, _Permission_name_0[_Permission_index_0[1]:_Permission_index_0[2]])
	}
	if i&4 != 0 {
		i, s = i&^4, append(s, _Permission_name_0[_Permission_index_0[2]:_Permission_index_0[3]])
	}
	if i != 0 {
		s = append(s, "Permission("+strconv.FormatUint(uint64(i), 10)+")")
	}
	return s
}

func (i Permission) String() string {
	return strings.Join(i.ActiveFlags(), "+")
}
